### ISSUE TITLE
Doesn't work with ied

### ISSUE THREAD

**Issue by chocolateboy** [ericelliott/rootrequire#2]
[ied](https://github.com/alexanderGugel/ied)'s [directory structure](https://github.com/alexanderGugel/ied#directory-structure) differs from that of npm. This is not handled correctly by rootrequire (or most similar modules).

**Comment by ericelliott** [comment]
If ied is meant to be an npm-compatible drop-in replacement, this should be filed as a bug against ied.

If it's not, I don't see a good reason to support it -- seems to me lots of modules will break.

Feel free to fork this module if you need ied support.
